const mongoose = require('mongoose');
const Producto = require('../../../server/models/productoModel');
const Categoria = require('../../../server/models/categoriaModel');

// Conectar a MongoDB
mongoose.connect('mongodb://localhost:27017/proyecto_grado', {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

const db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', async () => {
  console.log('Conectado a MongoDB');

  // Eliminar categorías existentes
  await Categoria.deleteMany({});

  // Crear categorías de ejemplo
  const categorias = [
    { nombreCategoria: 'Electrónica', descripcion: 'Artículos electrónicos' },
    { nombreCategoria: 'Ropa', descripcion: 'Artículos de ropa' },
    { nombreCategoria: 'Libros', descripcion: 'Libros y literatura' },
  ];

  const createdCategories = await Categoria.insertMany(categorias);

  // Eliminar productos existentes
  await Producto.deleteMany({});

  // productos de ejemplo

  const productos = [
    {
      idProducto: 'P001',
      nombreProducto: 'Portátil',
      descripcion: 'Un portátil de alto rendimiento',
      categoria: createdCategories[0]._id,
      precio: 999.99,
      stock: 50,
      proveedor: { nombre: 'Proveedor de Tecnología' },
      imagenURL: 'http://example.com/portatil.jpg',
      activo: true,
    },
    {
      idProducto: 'P002',
      nombreProducto: 'Camiseta',
      descripcion: 'Una camiseta de algodón cómoda',
      categoria: createdCategories[1]._id,
      precio: 19.99,
      stock: 200,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/camiseta.jpg',
      activo: true,
    },
    {
      idProducto: 'P003',
      nombreProducto: 'Libro',
      descripcion: 'Un libro fascinante',
      categoria: createdCategories[2]._id,
      precio: 14.99,
      stock: 100,
      proveedor: { nombre: 'Proveedor de Libros' },
      imagenURL: 'http://example.com/libro.jpg',
      activo: true,
    },
    // Añadir 30 productos más
    {
      idProducto: 'P004',
      nombreProducto: 'Smartphone',
      descripcion: 'Un smartphone de última generación',
      categoria: createdCategories[0]._id,
      precio: 699.99,
      stock: 150,
      proveedor: { nombre: 'Proveedor de Tecnología' },
      imagenURL: 'http://example.com/smartphone.jpg',
      activo: true,
    },
    {
      idProducto: 'P005',
      nombreProducto: 'Tablet',
      descripcion: 'Una tablet ligera y potente',
      categoria: createdCategories[0]._id,
      precio: 499.99,
      stock: 80,
      proveedor: { nombre: 'Proveedor de Tecnología' },
      imagenURL: 'http://example.com/tablet.jpg',
      activo: true,
    },
    {
      idProducto: 'P006',
      nombreProducto: 'Auriculares',
      descripcion: 'Auriculares con cancelación de ruido',
      categoria: createdCategories[0]._id,
      precio: 199.99,
      stock: 120,
      proveedor: { nombre: 'Proveedor de Tecnología' },
      imagenURL: 'http://example.com/auriculares.jpg',
      activo: true,
    },
    {
      idProducto: 'P007',
      nombreProducto: 'Cámara',
      descripcion: 'Cámara digital de alta resolución',
      categoria: createdCategories[0]._id,
      precio: 799.99,
      stock: 60,
      proveedor: { nombre: 'Proveedor de Tecnología' },
      imagenURL: 'http://example.com/camara.jpg',
      activo: true,
    },
    {
      idProducto: 'P008',
      nombreProducto: 'Reloj Inteligente',
      descripcion: 'Reloj inteligente con múltiples funciones',
      categoria: createdCategories[0]._id,
      precio: 299.99,
      stock: 90,
      proveedor: { nombre: 'Proveedor de Tecnología' },
      imagenURL: 'http://example.com/reloj.jpg',
      activo: true,
    },
    {
      idProducto: 'P009',
      nombreProducto: 'Televisor',
      descripcion: 'Televisor 4K Ultra HD',
      categoria: createdCategories[0]._id,
      precio: 1199.99,
      stock: 40,
      proveedor: { nombre: 'Proveedor de Tecnología' },
      imagenURL: 'http://example.com/televisor.jpg',
      activo: true,
    },
    {
      idProducto: 'P010',
      nombreProducto: 'Consola de Videojuegos',
      descripcion: 'Consola de videojuegos de última generación',
      categoria: createdCategories[0]._id,
      precio: 499.99,
      stock: 70,
      proveedor: { nombre: 'Proveedor de Tecnología' },
      imagenURL: 'http://example.com/consola.jpg',
      activo: true,
    },
    {
      idProducto: 'P011',
      nombreProducto: 'Zapatillas Deportivas',
      descripcion: 'Zapatillas deportivas cómodas y ligeras',
      categoria: createdCategories[1]._id,
      precio: 59.99,
      stock: 200,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/zapatillas.jpg',
      activo: true,
    },
    {
      idProducto: 'P012',
      nombreProducto: 'Chaqueta',
      descripcion: 'Chaqueta impermeable para exteriores',
      categoria: createdCategories[1]._id,
      precio: 89.99,
      stock: 150,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/chaqueta.jpg',
      activo: true,
    },
    {
      idProducto: 'P013',
      nombreProducto: 'Pantalones',
      descripcion: 'Pantalones de mezclilla de alta calidad',
      categoria: createdCategories[1]._id,
      precio: 49.99,
      stock: 180,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/pantalones.jpg',
      activo: true,
    },
    {
      idProducto: 'P014',
      nombreProducto: 'Vestido',
      descripcion: 'Vestido elegante para ocasiones especiales',
      categoria: createdCategories[1]._id,
      precio: 79.99,
      stock: 100,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/vestido.jpg',
      activo: true,
    },
    {
      idProducto: 'P015',
      nombreProducto: 'Sudadera',
      descripcion: 'Sudadera con capucha cómoda y cálida',
      categoria: createdCategories[1]._id,
      precio: 39.99,
      stock: 220,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/sudadera.jpg',
      activo: true,
    },
    {
      idProducto: 'P016',
      nombreProducto: 'Gorra',
      descripcion: 'Gorra ajustable de algodón',
      categoria: createdCategories[1]._id,
      precio: 19.99,
      stock: 300,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/gorra.jpg',
      activo: true,
    },
    {
      idProducto: 'P017',
      nombreProducto: 'Bufanda',
      descripcion: 'Bufanda de lana suave y cálida',
      categoria: createdCategories[1]._id,
      precio: 24.99,
      stock: 250,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/bufanda.jpg',
      activo: true,
    },
    {
      idProducto: 'P018',
      nombreProducto: 'Guantes',
      descripcion: 'Guantes de cuero elegantes',
      categoria: createdCategories[1]._id,
      precio: 29.99,
      stock: 200,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/guantes.jpg',
      activo: true,
    },
    {
      idProducto: 'P019',
      nombreProducto: 'Sombrero',
      descripcion: 'Sombrero de paja para el verano',
      categoria: createdCategories[1]._id,
      precio: 14.99,
      stock: 150,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/sombrero.jpg',
      activo: true,
    },
    {
      idProducto: 'P031',
      nombreProducto: 'Zapatillas Deportivas',
      descripcion: 'Zapatillas deportivas cómodas y ligeras',
      categoria: createdCategories[1]._id,
      precio: 59.99,
      stock: 200,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/zapatillas.jpg',
      activo: true,
    },
    {
      idProducto: 'P032',
      nombreProducto: 'Smartphone XYZ',
      descripcion: 'Smartphone de última generación con pantalla AMOLED y cámara de 108MP',
      categoria: createdCategories[0]._id,
      precio: 999.99,
      stock: 150,
      proveedor: { nombre: 'Proveedor de Electrónicos' },
      modelo: 'XYZ-2023',
      imagenURL: 'http://example.com/smartphone.jpg',
      activo: true,
    },
    {
      idProducto: 'P033',
      nombreProducto: 'Laptop ABC',
      descripcion: 'Laptop potente con procesador Intel i7 y 16GB de RAM',
      categoria: createdCategories[0]._id,
      precio: 1299.99,
      stock: 100,
      proveedor: { nombre: 'Proveedor de Electrónicos' },
      modelo: 'ABC-2023',
      imagenURL: 'http://example.com/laptop.jpg',
      activo: true,
    },
    {
      idProducto: 'P034',
      nombreProducto: 'Camiseta de Algodón',
      descripcion: 'Camiseta de algodón 100% suave y cómoda',
      categoria: createdCategories[1]._id,
      precio: 19.99,
      stock: 300,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/camiseta.jpg',
      activo: true,
    },
    {
      idProducto: 'P035',
      nombreProducto: 'Libro de Programación',
      descripcion: 'Libro sobre programación en JavaScript para principiantes',
      categoria: createdCategories[2]._id,
      precio: 29.99,
      stock: 250,
      proveedor: { nombre: 'Proveedor de Libros' },
      autor: 'John Doe',
      imagenURL: 'http://example.com/libro.jpg',
      activo: true,
    },
    {
      idProducto: 'P036',
      nombreProducto: 'Tablet DEF',
      descripcion: 'Tablet con pantalla de 10 pulgadas y 64GB de almacenamiento',
      categoria: createdCategories[0]._id,
      precio: 499.99,
      stock: 120,
      proveedor: { nombre: 'Proveedor de Electrónicos' },
      modelo: 'DEF-2023',
      imagenURL: 'http://example.com/tablet.jpg',
      activo: true,
    },
    {
      idProducto: 'P037',
      nombreProducto: 'Pantalones Vaqueros',
      descripcion: 'Pantalones vaqueros de alta calidad y durabilidad',
      categoria: createdCategories[1]._id,
      precio: 49.99,
      stock: 180,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/vaqueros.jpg',
      activo: true,
    },
    {
      idProducto: 'P038',
      nombreProducto: 'Libro de Cocina',
      descripcion: 'Libro con recetas de cocina internacional',
      categoria: createdCategories[2]._id,
      precio: 24.99,
      stock: 200,
      proveedor: { nombre: 'Proveedor de Libros' },
      autor: 'Jane Smith',
      imagenURL: 'http://example.com/libro-cocina.jpg',
      activo: true,
    },
  ];

  await Producto.insertMany(productos);
  console.log('Productos añadidos correctamente');
  mongoose.connection.close();
});
