const mongoose = require('mongoose');
const Producto = require('../../../server/models/productoModel');
const Categoria = require('../../../server/models/categoriaModel');

// Conectar a MongoDB
mongoose.connect('mongodb://localhost:27017/proyecto_grado', {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

const db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', async () => {
  console.log('Conectado a MongoDB');

  // Eliminar categorías existentes
  await Categoria.deleteMany({});

  // Crear categorías de ejemplo
  const categorias = [
    { nombreCategoria: 'Electrónica', descripcion: 'Artículos electrónicos' },
    { nombreCategoria: 'Ropa', descripcion: 'Artículos de ropa' },
    { nombreCategoria: 'Libros', descripcion: 'Libros y literatura' },
  ];

  const createdCategories = await Categoria.insertMany(categorias);

  // Eliminar productos existentes
  await Producto.deleteMany({});

  // Crear productos de ejemplo
  const productos = [
    {
      idProducto: 'P001',
      nombreProducto: 'Portátil',
      descripcion: 'Un portátil de alto rendimiento',
      categoria: createdCategories[0]._id,
      precio: 999.99,
      stock: 50,
      proveedor: { nombre: 'Proveedor de Tecnología' },
      imagenURL: 'http://example.com/portatil.jpg',
      activo: true,
    },
    {
      idProducto: 'P002',
      nombreProducto: 'Camiseta',
      descripcion: 'Una camiseta de algodón cómoda',
      categoria: createdCategories[1]._id,
      precio: 19.99,
      stock: 200,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/camiseta.jpg',
      activo: true,
    },
    {
      idProducto: 'P003',
      nombreProducto: 'Libro',
      descripcion: 'Un libro fascinante',
      categoria: createdCategories[2]._id,
      precio: 14.99,
      stock: 100,
      proveedor: { nombre: 'Proveedor de Libros' },
      imagenURL: 'http://example.com/libro.jpg',
      activo: true,
    },
    // Añadir 30 productos más
    {
      idProducto: 'P004',
      nombreProducto: 'Smartphone',
      descripcion: 'Un smartphone de última generación',
      categoria: createdCategories[0]._id,
      precio: 699.99,
      stock: 150,
      proveedor: { nombre: 'Proveedor de Tecnología' },
      imagenURL: 'http://example.com/smartphone.jpg',
      activo: true,
    },
    {
      idProducto: 'P005',
      nombreProducto: 'Tablet',
      descripcion: 'Una tablet ligera y potente',
      categoria: createdCategories[0]._id,
      precio: 499.99,
      stock: 80,
      proveedor: { nombre: 'Proveedor de Tecnología' },
      imagenURL: 'http://example.com/tablet.jpg',
      activo: true,
    },
    {
      idProducto: 'P006',
      nombreProducto: 'Auriculares',
      descripcion: 'Auriculares con cancelación de ruido',
      categoria: createdCategories[0]._id,
      precio: 199.99,
      stock: 120,
      proveedor: { nombre: 'Proveedor de Tecnología' },
      imagenURL: 'http://example.com/auriculares.jpg',
      activo: true,
    },
    {
      idProducto: 'P007',
      nombreProducto: 'Cámara',
      descripcion: 'Cámara digital de alta resolución',
      categoria: createdCategories[0]._id,
      precio: 799.99,
      stock: 60,
      proveedor: { nombre: 'Proveedor de Tecnología' },
      imagenURL: 'http://example.com/camara.jpg',
      activo: true,
    },
    {
      idProducto: 'P008',
      nombreProducto: 'Reloj Inteligente',
      descripcion: 'Reloj inteligente con múltiples funciones',
      categoria: createdCategories[0]._id,
      precio: 299.99,
      stock: 90,
      proveedor: { nombre: 'Proveedor de Tecnología' },
      imagenURL: 'http://example.com/reloj.jpg',
      activo: true,
    },
    {
      idProducto: 'P009',
      nombreProducto: 'Televisor',
      descripcion: 'Televisor 4K Ultra HD',
      categoria: createdCategories[0]._id,
      precio: 1199.99,
      stock: 40,
      proveedor: { nombre: 'Proveedor de Tecnología' },
      imagenURL: 'http://example.com/televisor.jpg',
      activo: true,
    },
    {
      idProducto: 'P010',
      nombreProducto: 'Consola de Videojuegos',
      descripcion: 'Consola de videojuegos de última generación',
      categoria: createdCategories[0]._id,
      precio: 499.99,
      stock: 70,
      proveedor: { nombre: 'Proveedor de Tecnología' },
      imagenURL: 'http://example.com/consola.jpg',
      activo: true,
    },
    {
      idProducto: 'P011',
      nombreProducto: 'Zapatillas Deportivas',
      descripcion: 'Zapatillas deportivas cómodas y ligeras',
      categoria: createdCategories[1]._id,
      precio: 59.99,
      stock: 200,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/zapatillas.jpg',
      activo: true,
    },
    {
      idProducto: 'P012',
      nombreProducto: 'Chaqueta',
      descripcion: 'Chaqueta impermeable para exteriores',
      categoria: createdCategories[1]._id,
      precio: 89.99,
      stock: 150,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/chaqueta.jpg',
      activo: true,
    },
    {
      idProducto: 'P013',
      nombreProducto: 'Pantalones',
      descripcion: 'Pantalones de mezclilla de alta calidad',
      categoria: createdCategories[1]._id,
      precio: 49.99,
      stock: 180,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/pantalones.jpg',
      activo: true,
    },
    {
      idProducto: 'P014',
      nombreProducto: 'Vestido',
      descripcion: 'Vestido elegante para ocasiones especiales',
      categoria: createdCategories[1]._id,
      precio: 79.99,
      stock: 100,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/vestido.jpg',
      activo: true,
    },
    {
      idProducto: 'P015',
      nombreProducto: 'Sudadera',
      descripcion: 'Sudadera con capucha cómoda y cálida',
      categoria: createdCategories[1]._id,
      precio: 39.99,
      stock: 220,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/sudadera.jpg',
      activo: true,
    },
    {
      idProducto: 'P016',
      nombreProducto: 'Gorra',
      descripcion: 'Gorra ajustable de algodón',
      categoria: createdCategories[1]._id,
      precio: 19.99,
      stock: 300,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/gorra.jpg',
      activo: true,
    },
    {
      idProducto: 'P017',
      nombreProducto: 'Bufanda',
      descripcion: 'Bufanda de lana suave y cálida',
      categoria: createdCategories[1]._id,
      precio: 24.99,
      stock: 250,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/bufanda.jpg',
      activo: true,
    },
    {
      idProducto: 'P018',
      nombreProducto: 'Guantes',
      descripcion: 'Guantes de cuero elegantes',
      categoria: createdCategories[1]._id,
      precio: 29.99,
      stock: 200,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/guantes.jpg',
      activo: true,
    },
    {
      idProducto: 'P019',
      nombreProducto: 'Sombrero',
      descripcion: 'Sombrero de paja para el verano',
      categoria: createdCategories[1]._id,
      precio: 14.99,
      stock: 150,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/sombrero.jpg',
      activo: true,
    },
    {
      idProducto: 'P020',
      nombreProducto: 'Cinturón',
      descripcion: 'Cinturón de cuero genuino',
      categoria: createdCategories[1]._id,
      precio: 34.99,
      stock: 180,
      proveedor: { nombre: 'Proveedor de Ropa' },
      imagenURL: 'http://example.com/cinturon.jpg',
      activo: true,
    },
    {
      idProducto: 'P021',
      nombreProducto: 'Libro de Cocina',
      descripcion: 'Libro de recetas de cocina internacional',
      categoria: createdCategories[2]._id,
      precio: 29.99,
      stock: 120,
      proveedor: { nombre: 'Proveedor de Libros' },
      imagenURL: 'http://example.com/libro_cocina.jpg',
      activo: true,
    },
    {
      idProducto: 'P022',
      nombreProducto: 'Novela',
      descripcion: 'Novela de ficción emocionante',
      categoria: createdCategories[2]._id,
      precio: 19.99,
      stock: 200,
      proveedor: { nombre: 'Proveedor de Libros' },
      imagenURL: 'http://example.com/novela.jpg',
      activo: true,
    },
    {
      idProducto: 'P023',
      nombreProducto: 'Libro de Historia',
      descripcion: 'Libro sobre la historia mundial',
      categoria: createdCategories[2]._id,
      precio: 24.99,
      stock: 150,
      proveedor: { nombre: 'Proveedor de Libros' },
      imagenURL: 'http://example.com/libro_historia.jpg',
      activo: true,
    },
    {
      idProducto: 'P024',
      nombreProducto: 'Libro de Ciencia',
      descripcion: 'Libro sobre descubrimientos científicos',
      categoria: createdCategories[2]._id,
      precio: 34.99,
      stock: 100,
      proveedor: { nombre: 'Proveedor de Libros' },
      imagenURL: 'http://example.com/libro_ciencia.jpg',
      activo: true,
    },
    {
      idProducto: 'P025',
      nombreProducto: 'Libro de Arte',
      descripcion: 'Libro sobre historia del arte',
      categoria: createdCategories[2]._id,
      precio: 39.99,
      stock: 80,
      proveedor: { nombre: 'Proveedor de Libros' },
      imagenURL: 'http://example.com/libro_arte.jpg',
      activo: true,
    },
    {
      idProducto: 'P026',
      nombreProducto: 'Libro de Viajes',
      descripcion: 'Guía de viajes por el mundo',
      categoria: createdCategories[2]._id,
      precio: 29.99,
      stock: 90,
      proveedor: { nombre: 'Proveedor de Libros' },
      imagenURL: 'http://example.com/libro_viajes.jpg',
      activo: true,
    },
    {
      idProducto: 'P027',
      nombreProducto: 'Libro Infantil',
      descripcion: 'Libro de cuentos para niños',
      categoria: createdCategories[2]._id,
      precio: 14.99,
      stock: 200,
      proveedor: { nombre: 'Proveedor de Libros' },
      imagenURL: 'http://example.com/libro_infantil.jpg',
      activo: true,
    },
    {
      idProducto: 'P028',
      nombreProducto: 'Libro de Autoayuda',
      descripcion: 'Libro de desarrollo personal',
      categoria: createdCategories[2]._id,
      precio: 19.99,
      stock: 180,
      proveedor: { nombre: 'Proveedor de Libros' },
      imagenURL: 'http://example.com/libro_autoayuda.jpg',
      activo: true,
    },
    {
      idProducto: 'P029',
      nombreProducto: 'Libro de Negocios',
      descripcion: 'Libro sobre estrategias empresariales',
      categoria: createdCategories[2]._id,
      precio: 24.99,
      stock: 150,
      proveedor: { nombre: 'Proveedor de Libros' },
      imagenURL: 'http://example.com/libro_negocios.jpg',
      activo: true,
    },
    {
      idProducto: 'P030',
      nombreProducto: 'Libro de Salud',
      descripcion: 'Libro sobre bienestar y salud',
      categoria: createdCategories[2]._id,
      precio: 29.99,
      stock: 120,
      proveedor: { nombre: 'Proveedor de Libros' },
      imagenURL: 'http://example.com/libro_salud.jpg',
      activo: true,
    },
  ];

  await Producto.insertMany(productos);
  console.log('Productos añadidos correctamente');
  mongoose.connection.close();
});